name: Build and Deploy

on: workflow_dispatch

env:
  ENVS: "envs"

# for AWS credentials and k8s setting
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      # checkout branch
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        id: login-to-docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/aws-secret-updater:${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/aws-secret-updater:latest
