name: Build and Deploy

on: workflow_dispatch

env:
  ENVS: "envs"

# for AWS credentials and k8s setting
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      # checkout branch
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CONNECT_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to AWS ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ steps.login-to-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY_NAME }}:${{ github.sha }}
            ${{ steps.login-to-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY_NAME }}:latest
